### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by S-DICKSON** [S-DICKSON/spacebook-react#1]
This is is to track what tasks need to completed for the Login page.

**TODO**

- [x] Navigation to home page
- [x] Navigation register page
- [x] Login user
- [x] Error handling of logging in
