### ISSUE TITLE
Register page

### ISSUE THREAD

**Issue by S-DICKSON** [S-DICKSON/spacebook-react#3]
**To-do**
- [x] Create register form
- [x] Validation for the form
- [x] Flash message if successful 
- [x] Flash message if error (i.e an account already exists with that details)

**Resources**
- https://medium.com/@acatomas/create-a-react-native-fully-controlled-form-using-react-hook-form-react-native-paper-and-e34c9ec11e5f
- https://www.npmjs.com/package/react-native-flash-message
